// FILE: src/main/java/com/dermosphere/backend/repository/AuditLogRepository.java
package com.dermosphere.backend.repository;

import com.dermosphere.backend.entity.SystemAuditLog;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

@Repository
public interface AuditLogRepository extends JpaRepository<SystemAuditLog, Long> {
    // Basic CRUD operations are automatically generated by Spring Data JPA
}