server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/dermosphere_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=update

spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.connection-timeout=20000

management.endpoints.web.exposure.include=health,metrics,prometheus
management.endpoint.health.show-details=always

ai.microservice.url=http://127.0.0.1:8000/api/v1/triage/predict
spring.servlet.multipart.max-file-size=10MB
spring.codec.max-in-memory-size=10MB

logging.level.io.netty.resolver.dns=DEBUG
logging.level.reactor.netty=DEBUG